import { Theme } from '../types';

export const THEMES: Theme[] = [
  {
    id: 'theme-blue',
    name: 'Default Blue',
    bg: { primary: '#0f172a', secondary: '#1e293b', tertiary: '#334155' },
    text: { primary: '#e2e8f0', secondary: '#94a3b8', placeholder: '#64748b' },
    accent: { gradient: 'linear-gradient(to right, #2563eb, #3b82f6)', primary: '#3b82f6' },
    font: "'Inter', sans-serif",
  },
  {
    id: 'theme-emerald',
    name: 'Emerald Green',
    bg: { primary: '#061a13', secondary: '#062d1f', tertiary: '#05402c' },
    text: { primary: '#d1fae5', secondary: '#a7f3d0', placeholder: '#6ee7b7' },
    accent: { gradient: 'linear-gradient(to right, #059669, #10b981)', primary: '#10b981' },
    font: "'Inter', sans-serif",
  },
  {
    id: 'theme-rose',
    name: 'Rose Pink',
    bg: { primary: '#2a0610', secondary: '#4d0b1d', tertiary: '#6d142b' },
    text: { primary: '#ffe4e6', secondary: '#fecdd3', placeholder: '#fda4af' },
    accent: { gradient: 'linear-gradient(to right, #e11d48, #f43f5e)', primary: '#f43f5e' },
    font: "'Inter', sans-serif",
  },
  {
    id: 'theme-violet',
    name: 'Violet',
    bg: { primary: '#1a102f', secondary: '#2a1a4a', tertiary: '#3b2569' },
    text: { primary: '#ede9fe', secondary: '#ddd6fe', placeholder: '#c4b5fd' },
    accent: { gradient: 'linear-gradient(to right, #7c3aed, #8b5cf6)', primary: '#8b5cf6' },
    font: "'Inter', sans-serif",
  },
  {
    id: 'theme-amber',
    name: 'Amber',
    bg: { primary: '#2a1a02', secondary: '#4a2f05', tertiary: '#694309' },
    text: { primary: '#fef3c7', secondary: '#fde68a', placeholder: '#fcd34d' },
    accent: { gradient: 'linear-gradient(to right, #d97706, #f59e0b)', primary: '#f59e0b' },
    font: "'Inter', sans-serif",
  },
    {
    id: 'theme-halloween',
    name: 'Halloween',
    bg: { primary: '#0d0d0d', secondary: '#1a0e24', tertiary: '#2b163d' },
    text: { primary: '#f3e8ff', secondary: '#e9d5ff', placeholder: '#d8b4fe' },
    accent: { gradient: 'linear-gradient(to right, #f97316, #ea580c)', primary: '#f97316' },
    font: "'Creepster', cursive",
  },
  {
    id: 'theme-christmas',
    name: 'Christmas',
    bg: { primary: '#0a1d13', secondary: '#12372a', tertiary: '#0c4b33' },
    text: { primary: '#fef2f2', secondary: '#fee2e2', placeholder: '#fca5a5' },
    accent: { gradient: 'linear-gradient(to right, #dc2626, #ef4444)', primary: '#dc2626' },
    font: "'Inter', sans-serif",
  },
    {
    id: 'theme-lunar-new-year',
    name: 'Lunar New Year',
    bg: { primary: '#2d0d0d', secondary: '#4e1616', tertiary: '#6e2121' },
    text: { primary: '#fffbeb', secondary: '#fef3c7', placeholder: '#fde68a' },
    accent: { gradient: 'linear-gradient(to right, #fcd34d, #fbbf24)', primary: '#fcd34d' },
    font: "'Inter', sans-serif",
  },
  {
    id: 'theme-spring',
    name: 'Spring',
    bg: { primary: '#f0fdf4', secondary: '#dcfce7', tertiary: '#bbf7d0' },
    text: { primary: '#14532d', secondary: '#166534', placeholder: '#15803d' },
    accent: { gradient: 'linear-gradient(to right, #ec4899, #f472b6)', primary: '#ec4899' },
    font: "'Inter', sans-serif",
  },
  {
    id: 'theme-matrix',
    name: 'Matrix',
    bg: { primary: '#000000', secondary: 'rgba(0, 255, 65, 0.05)', tertiary: 'rgba(0, 255, 65, 0.1)' },
    text: { primary: '#00FF41', secondary: '#008F11', placeholder: '#003B00' },
    accent: { gradient: 'linear-gradient(to right, #00FF41, #008F11)', primary: '#00FF41' },
    font: "'Share Tech Mono', monospace",
  },
];
